# Generated by Django 5.2.7 on 2025-10-16 14:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Backup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("archivo", models.FileField(upload_to="backups/")),
                (
                    "fecha_creacion",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("tamaño", models.CharField(max_length=20)),
                ("estado", models.CharField(max_length=20)),
                ("notas", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-fecha_creacion"],
            },
        ),
    ]
