# Generated by Django 6.0.4 on 2026-04-19 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Backup',
        ),
    ]
