# Generated by Django 5.2.12 on 2026-03-16 14:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividad', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='registroactividad',
            name='datos_antes',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registroactividad',
            name='datos_despues',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registroactividad',
            name='objeto_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registroactividad',
            name='objeto_tipo',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='registroactividad',
            name='tipo_accion',
            field=models.CharField(choices=[('CREATE', 'Creación'), ('UPDATE', 'Modificación'), ('DELETE', 'Eliminación'), ('LOGIN', 'Inicio de sesión'), ('LOGOUT', 'Cierre de sesión'), ('APPROVE', 'Aprobación'), ('REJECT', 'Rechazo'), ('CANCEL', 'Cancelación'), ('EXPORT', 'Exportación'), ('OTHER', 'Otro')], default='OTHER', max_length=20),
        ),
        migrations.AddIndex(
            model_name='registroactividad',
            index=models.Index(fields=['modulo'], name='actividad_r_modulo_a49d19_idx'),
        ),
        migrations.AddIndex(
            model_name='registroactividad',
            index=models.Index(fields=['tipo_accion'], name='actividad_r_tipo_ac_306f13_idx'),
        ),
        migrations.AddIndex(
            model_name='registroactividad',
            index=models.Index(fields=['usuario'], name='actividad_r_usuario_78aca3_idx'),
        ),
        migrations.AddIndex(
            model_name='registroactividad',
            index=models.Index(fields=['fecha'], name='actividad_r_fecha_f62e5b_idx'),
        ),
        migrations.AddIndex(
            model_name='registroactividad',
            index=models.Index(fields=['objeto_tipo', 'objeto_id'], name='actividad_r_objeto__41a2fd_idx'),
        ),
        migrations.AddIndex(
            model_name='registroactividad',
            index=models.Index(fields=['modulo', 'fecha'], name='actividad_r_modulo_7feb11_idx'),
        ),
        migrations.AddIndex(
            model_name='registroactividad',
            index=models.Index(fields=['usuario', 'fecha'], name='actividad_r_usuario_3d0f40_idx'),
        ),
    ]
