# Generated by Django 5.2.12 on 2026-03-16 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0001_initial'),
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='doc_propietario',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='equipo',
            name='es_externo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='equipo',
            name='propietario_externo',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='equipo',
            name='reserva_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipos_externos', to='reservas.reserva'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('en_uso', 'En uso'), ('mantenimiento', 'Mantenimiento'), ('dañado', 'Dañado'), ('retirado', 'Retirado')], default='disponible', max_length=20),
        ),
    ]
