# Generated by Django 5.2.12 on 2026-03-16 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0002_equipo_doc_propietario_equipo_es_externo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='fecha_adquisicion',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='valor',
        ),
    ]
