# Generated by Django 6.0.4 on 2026-04-17 22:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0004_movimientoequipo_estado_motivo_rechazo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cambio', models.CharField(choices=[('estado', 'Cambio de Estado'), ('ambiente', 'Cambio de Ambiente'), ('responsable', 'Cambio de Responsable'), ('caracteristica', 'Cambio de Característica'), ('movimiento', 'Movimiento Registrado'), ('otro', 'Otro Cambio')], max_length=20)),
                ('campo', models.CharField(help_text='Campo que fue modificado', max_length=100)),
                ('valor_anterior', models.TextField(blank=True, null=True)),
                ('valor_nuevo', models.TextField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del cambio realizado')),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='equipos.equipo')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_equipos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Equipo',
                'verbose_name_plural': 'Historial de Equipos',
                'db_table': 'historial_equipos',
                'ordering': ['-fecha_cambio'],
                'indexes': [models.Index(fields=['equipo', '-fecha_cambio'], name='historial_e_equipo__d565ce_idx')],
            },
        ),
    ]
