# Generated by Django 5.2.6 on 2025-10-13 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ambiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('capacidad', models.PositiveIntegerField()),
                ('tipo', models.CharField(choices=[('aula', 'Aula'), ('laboratorio', 'Laboratorio'), ('taller', 'Taller'), ('auditorio', 'Auditorio'), ('biblioteca', 'Biblioteca')], max_length=20)),
                ('ubicacion', models.CharField(blank=True, max_length=100)),
                ('recursos', models.JSONField(blank=True, default=dict, help_text='JSON con recursos disponibles', null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ambiente',
                'verbose_name_plural': 'Ambientes',
                'db_table': 'ambientes',
                'ordering': ['codigo'],
            },
        ),
    ]
