# Generated by Django 5.2.3 on 2025-10-16 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambiente',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
