# Generated by Django 6.0.1 on 2026-01-20 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('instructor', 'Instructor'), ('administrativo', 'Administrativo'), ('coordinador', 'Coordinador'), ('admin', 'Administrador'), ('usuario', 'Usuario')], default='usuario', max_length=20),
        ),
    ]
