# Generated by Django 5.2.10 on 2026-02-05 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_usuario_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudCambioRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol_actual', models.CharField(choices=[('instructor', 'Instructor'), ('administrativo', 'Administrativo'), ('coordinador', 'Coordinador'), ('admin', 'Administrador'), ('usuario', 'Usuario')], max_length=20)),
                ('rol_solicitado', models.CharField(choices=[('instructor', 'Instructor'), ('administrativo', 'Administrativo'), ('coordinador', 'Coordinador'), ('admin', 'Administrador'), ('usuario', 'Usuario')], max_length=20)),
                ('razon', models.TextField(blank=True, verbose_name='Razón de la solicitud')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('comentario_admin', models.TextField(blank=True, verbose_name='Comentario del administrador')),
                ('respondido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_respondidas', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_rol', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de Cambio de Rol',
                'verbose_name_plural': 'Solicitudes de Cambio de Rol',
                'db_table': 'solicitudes_cambio_rol',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
