# Generated by Django 5.2.10 on 2026-02-27 16:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_solicitudcambiorol'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tipo_documento',
            field=models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cédula de Extranjería'), ('PEP', 'PEP'), ('PPT', 'Permiso por Protección Temporal')], default='CC', max_length=10, verbose_name='Tipo de documento'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='documento',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Solo letras y números permitidos', regex='^[A-Za-z0-9]+$')]),
        ),
    ]
