# Generated by Django 5.2.12 on 2026-03-16 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_usuario_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='fecha_actualizacion',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='tipo_documento',
        ),
    ]
