# Generated by Django 6.0.4 on 2026-04-17 22:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cambio', models.CharField(choices=[('estado', 'Cambio de Estado'), ('fechas', 'Cambio de Fechas'), ('ambiente', 'Cambio de Ambiente'), ('detalles', 'Cambio de Detalles'), ('aprobacion', 'Aprobación'), ('rechazo', 'Rechazo'), ('cancelacion', 'Cancelación'), ('otro', 'Otro Cambio')], max_length=20)),
                ('campo', models.CharField(blank=True, help_text='Campo que fue modificado', max_length=100)),
                ('valor_anterior', models.TextField(blank=True, null=True)),
                ('valor_nuevo', models.TextField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del cambio realizado')),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='reservas.reserva')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_reservas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Reserva',
                'verbose_name_plural': 'Historial de Reservas',
                'db_table': 'historial_reservas',
                'ordering': ['-fecha_cambio'],
                'indexes': [models.Index(fields=['reserva', '-fecha_cambio'], name='historial_r_reserva_c5eb6f_idx')],
            },
        ),
    ]
